### ISSUE TITLE
question: how can I include resourse, for example: image

### ISSUE THREAD

**Issue by zhangaz1** [luciopaiva/witchcraft#34]

**Comment by luciopaiva** [comment]
That's a very nice question.

There is currently no way of directly including resource types other than JS and CSS. However, you could try one of these tricks:

- embed the resource into your JS file: here's [an example](https://stackoverflow.com/a/16449483/778272). You'd just need to get a base64 representation of the image;
- embed the resource into your CSS file: [this article](https://css-tricks.com/data-uris/) shows an example. The same conversion to base 64 applies;
- use the local web server to retrieve the image: since Witchcraft relies on a local web server running, that same web server can be used by your script to load an image, so you don't have to embed it like the two previous options. Move the resource to the same folder where your Witchcraft scripts live, open your Witchcraft pop-up window, copy the web server address from there, then append to it the name of your resource file (e.g. `http://127.0.0.1:5743/foo.png`). You can then use this address to load your image directly.

I'd go with the last option, which seems to be the easiest. Please let me know if you were able to do it.

**Comment by luciopaiva** [comment]
Added this question to the [FAQ](https://luciopaiva.com/witchcraft/faq.html). I am closing the issue, but please feel free to continue the discussion if you'd like to.

**Comment by luciopaiva** [comment]
Notice that you may have run into CORS issues when trying to fetch resources from `http://127.0.0.1:5743`. Configure your HTTP scripts server to set the proper CORS headers.

If using the recommended Web Server Chrome app, open its settings, click "Show Advanced Options" and then check the "Set CORS headers" option.

![image](https://user-images.githubusercontent.com/6631859/117574042-1ad9c700-b0d3-11eb-82ba-d3abdeccb5cd.png)
